export const uniqueControlRecords = [
  'AESINITIAL',
  'AES',
  'ANNEAL',
  'BIND',
  'CHAIN',
  'CONTR',
  'DATA',
  'DEFAULT',
  'DESIGN',
  'DES',
  'ETAS',
  'PHIS',
  'FORMAT',
  'INDEX',
  'INFN',
  'INPUT',
  'LEVEL',
  'MIX',
  'MODEL',
  'MSFI',
  'NONPARAMETRIC',
  'OLKJDF',
  'OMEGAPD',
  'OMEGAP',
  'OMEGA',
  'OMIT',
  'OVARF',
  'PK',
  'PRED',
  'PRIOR',
  'RCOVI',
  'RCOV',
  'SIGMAPD',
  'SIGMAP',
  'SIGMA',
  'SIZES',
  'SLKJDF',
  'SUPER',
  'SVARF',
  'THETAPV',
  'THETAP',
  'THETAI',
  'THETAR',
  'THETA',
  'TOL',
  'TTDF',
  'WARNINGS'
];

export const abbreviatableControlRecords = [
  'ABBREVIATED',
  'COVARIANCE',
  'ESTIMATION',
  'ERROR',
  'PROBLEM',
  'SCATTERPLOT',
  'SIMULATION',
  'SUBROUTINES',
  'TABLE'
];

export const aliasControlRecords: Record<string, string> = { // Type hack
  'COVR': 'COVARIANCE',
  'ESTIMATE': 'ESTIMATION',
  'ESTM': 'ESTIMATION',
  'INFILE': 'DATA',
  'INDXS': 'INDEX',
  'INPT': 'INPUT',
  'SIMULATE': 'SIMULATION',
  'SIML': 'SIMULATION',
  'SUBS': 'SUBROUTINES',
  'THTA': 'THETA',
  'THR': 'THETAR',
  'THI': 'THETAI',
};

export const validSizesOptions = [
  'LTH',
  'LVR',
  'LVR2',
  'NO',
  'MMX',
  'LNP4',
  'LSUPP',
  'LIM7',
  'LWS3',
  'MAXIDS',
  'LIM1',
  'LIM2',
  'LIM3',
  'LIM4',
  'LIM5',
  'LIM6',
  'LIM8',
  'LIM11',
  'LIM13',
  'LIM15',
  'LIM16',
  'MAXRECID',
  'PC',
  'PCT',
  'PIR',
  'PD',
  'PDT',
  'PAL',
  'MAXFCN',
  'DIMTMP',
  'DIMCNS',
  'DIMNEW',
  'DIMVRB',
  'PL',
  'NPOPMIXMAX',
  'MAXOMEG',
  'MAXPTHETA',
  'MAXITER',
  'ISAMPLEMAX',
  'MAXSIDL',
  'PNM_MAXNODES',
  'MAXNRDS',
  'PAST_SIZE',
];

export const reservedDataItemLabels = [
  'ID',
  'L1',
  'L2',
  'DV',
  'MDV',
  'TIME',
  'DATE',
  'DAT1',
  'DAT2',
  'DAT3',
  'DROP',
  'SKIP',
  'EVID',
  'AMT',
  'RATE',
  'SS',
  'II',
  'ADDL',
  'RAW_',
  'MRG_',
  'RPT_',
  'REPL_'
];

export const statementKeywords = {
  'statement-if': ['IF', 'THEN', 'ELSE', 'ELSEIF', 'ENDIF'],
  'statement-while': ['DO WHILE', 'ENDDO'],
  'statement-other': ['CALL', 'WRITE', 'PRINT', 'RETURN', 'OPEN', 'CLOSE', 'REWIND'],
  'statement-exit': 'EXIT',
  'nonmem_protect': ['PLOG10', 'PLOG', 'PEXP', 'PSQRT', 'PDZ', 'PNP', 'PHE', 'PNG', 'PTAN', 'PASIN', 'PACOS', 'PATAN'],
  'nonmem_builtin': ['PHI', 'GAMLN', 'DLOG', 'DEXP', 'DSQRT'],
  'fortran_builtin': ['LOG10', 'LOG', 'EXP', 'SQRT', 'SIN', 'COS', 'TAN', 'ASIN', 'ACOS', 'ATAN', 'ABS', 'INT', 'MIN', 'MAX', 'MOD'],
  'theta': 'THETA',
  'eta': 'ETA',
  'epsilon': ['EPS', 'ERR'],
};

export const validControlRecords = [
  '$ABBREVIATED',
  '$AES',
  '$AESINITIAL',
  '$ANNEAL',
  '$BIND',
  '$CHAIN',
  '$CONTR',
  '$COVARIANCE',
  '$COVR',
  '$DATA',
  '$DEFAULT',
  '$DES',
  '$DESIGN',
  '$ERROR',
  '$ESTIMATION',
  '$ESTIMATE',
  '$ESTM',
  '$ETAS',
  '$PHIS',
  '$FORMAT',
  '$INDEX',
  '$INDXS',
  '$INFN',
  '$INPUT',
  '$LEVEL',
  '$MIX',
  '$MODEL',
  '$MSFI',
  '$NONPARAMETRIC',
  '$OLKJDF',
  '$OMEGA',
  '$OMEGAP',
  '$OMEGAPD',
  '$OMIT',
  '$OVARF',
  '$PK',
  '$PRED',
  '$PRIOR',
  '$PROBLEM',
  '$RCOV',
  '$RCOVI',
  '$SCATTERPLOT',
  '$SIGMA',
  '$SIGMAP',
  '$SIGMAPD',
  '$SIMULATION',
  '$SIMULATE',
  '$SIML',
  '$SIZES',
  '$SLKJDF',
  '$SUBROUTINES',
  '$SUPER',
  '$SVARF',
  '$TABLE',
  '$THETA',
  '$THI',
  '$THETAI',
  '$THETAP',
  '$THETAPV',
  '$THR',
  '$THETAR',
  '$TOL',
  '$TTDF',
  '$WARNINGS'
];