/**
 * NMTRAN Control Records Dictionary
 * 
 * Complete list of valid NMTRAN control records for validation.
 * Add new control records here when NONMEM adds them.
 * Keep alphabetically sorted for easy maintenance.
 */
export const allowedControlRecords = [
  '$ABBREVIATED',
  '$AES',
  '$AESINITIAL',
  '$ANNEAL',
  '$BIND',
  '$CHAIN',
  '$CONTR',
  '$COVARIANCE',
  '$COVR',
  '$DATA',
  '$DEFAULT',
  '$DES',
  '$DESIGN',
  '$ERROR',
  '$ESTIMATION',
  '$ESTIMATE',
  '$ESTM',
  '$ETAS',
  '$PHIS',
  '$FORMAT',
  '$INDEX',
  '$INDXS',
  '$INFN',
  '$INPUT',
  '$LEVEL',
  '$MIX',
  '$MODEL',
  '$MSFI',
  '$NONPARAMETRIC',
  '$OLKJDF',
  '$OMEGA',
  '$OMEGAP',
  '$OMEGAPD',
  '$OMIT',
  '$OVARF',
  '$PK',
  '$PRED',
  '$PRIOR',
  '$PROBLEM',
  '$RCOV',
  '$RCOVI',
  '$SCATTERPLOT',
  '$SIGMA',
  '$SIGMAP',
  '$SIGMAPD',
  '$SIMULATION',
  '$SIMULATE',
  '$SIML',
  '$SIZES',
  '$SLKJDF',
  '$SUBROUTINES',
  '$SUPER',
  '$SVARF',
  '$TABLE',
  '$THETA',
  '$THI',
  '$THETAI',
  '$THETAP',
  '$THETAPV',
  '$THETAR',
  '$THR',
  '$TOL',
  '$TTDF',
  '$WARNINGS'
];

/**
 * NMTRAN Reserved Variables
 * 
 * Special variables with predefined meanings in NMTRAN abbreviated code.
 */
export const reservedVariables = [
  'ICALL',    // Execution context indicator
  'NEWIND',   // Individual record indicator  
  'Y',        // Mandatory left-hand quantity for PRED
  'ERR'       // Alternative to ETA/EPS arrays
];

/**
 * NMTRAN Reserved Functions and Vectors (NONMEM 7.4+)
 * 
 * Reserved function names FUNCA through FUNCZ and vector names VECTRA through VECTRZ.
 */
export const reservedFunctions = [
  // Reserved functions A-Z
  ...Array.from({length: 26}, (_, i) => `FUNC${String.fromCharCode(65 + i)}`),
  // Reserved vectors A-Z  
  ...Array.from({length: 26}, (_, i) => `VECTR${String.fromCharCode(65 + i)}`)
];

/**
 * NMTRAN Protective Functions (NONMEM 7.4+)
 * 
 * Functions that protect against domain violations and floating point errors.
 */
export const protectiveFunctions = [
  'PLOG', 'PEXP', 'PSQRT', 'PSIN', 'PCOS', 'PTAN'
];

/**
 * NMTRAN Generated Files
 * 
 * Files automatically generated by NMTRAN during translation process.
 */
export const generatedFiles = [
  'FDATA', 'FCON', 'FSTREAM', 'FREPORT', 'FLIB', 'LINK'
];
